FOG_DIRECTORY: 'ferrisamericus'
AWS_ACCESS_KEY_ID: 'AKIAJJYLJYJZKWVHN2XA'
AWS_SECRET_ACCESS_KEY: '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'
CLOUDFRONT_DISTRIBUTION_DOMAIN: 'http://dok4m4b91bmhc.cloudfront.net'